static const char gladestring [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.18.3 --><interface><requires lib=\"gtk+\" ve"
  "rsion=\"3.12\"/><!-- interface-license-type gplv3 --><!-- interface-name Gtk3Run --><!-- interfa"
  "ce-description Gtk3 Run Command --><!-- interface-authors J. M. Becker <cyberpunkspike@gmail.com"
  "> --><object class=\"GtkListStore\" id=\"liststore1\"><columns><!-- column-name COL_NAME --><col"
  "umn type=\"gchararray\"/><!-- column-name gint1 --><column type=\"gint\"/></columns></object><ob"
  "ject class=\"GtkEntryCompletion\" id=\"entrycompletion1\"><property name=\"model\">liststore1</p"
  "roperty><property name=\"text_column\">0</property><signal handler=\"cb_matchselected\" name=\"m"
  "atch-selected\" swapped=\"no\"/><child><object class=\"GtkCellRendererText\" id=\"textCellRender"
  "er\"><property name=\"ypad\">1</property></object><attributes><attribute name=\"text\">0</attrib"
  "ute></attributes></child></object><object class=\"GtkWindow\" id=\"window1\"><property name=\"ca"
  "n_focus\">False</property><property name=\"title\" translatable=\"yes\">Run Command</property><p"
  "roperty name=\"resizable\">False</property><property name=\"window_position\">center</property><"
  "property name=\"type_hint\">dialog</property><property name=\"decorated\">False</property><signa"
  "l handler=\"cb_destroy\" name=\"destroy\" swapped=\"no\"/><child><object class=\"GtkBox\" id=\"b"
  "ox1\"><property name=\"visible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"orientation\">vertical</property><child><object class=\"GtkEntry\" id=\"entry1\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"margin_left\">4</property><property name=\"margin_right\">4</property><property name=\"mar"
  "gin_top\">4</property><property name=\"width_chars\">60</property><property name=\"caps_lock_war"
  "ning\">False</property><property name=\"primary_icon_activatable\">False</property><property nam"
  "e=\"secondary_icon_activatable\">False</property><property name=\"primary_icon_sensitive\">False"
  "</property><property name=\"secondary_icon_sensitive\">False</property><property name=\"placehol"
  "der_text\" translatable=\"yes\">Run Command:</property><property name=\"completion\">entrycomple"
  "tion1</property><property name=\"input_hints\">GTK_INPUT_HINT_WORD_COMPLETION | GTK_INPUT_HINT_N"
  "ONE</property><signal handler=\"cb_activate\" name=\"activate\" object=\"statusbar1\" swapped=\""
  "no\"/><signal handler=\"cb_changed\" name=\"changed\" swapped=\"no\"/><signal handler=\"cb_keypr"
  "ess\" name=\"key-press-event\" swapped=\"no\"/></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">True</property><property name=\"position\">1</property></pack"
  "ing></child><child><object class=\"GtkStatusbar\" id=\"statusbar1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property name=\"margin_left\">12</pr"
  "operty><property name=\"margin_right\">12</property><property name=\"margin_start\">10</property"
  "><property name=\"margin_end\">10</property><property name=\"orientation\">vertical</property><s"
  "ignal handler=\"cb_pushed\" name=\"text-pushed\" swapped=\"no\"/></object><packing><property nam"
  "e=\"expand\">False</property><property name=\"fill\">True</property><property name=\"position\">"
  "2</property></packing></child></object></child></object></interface>"
};
