static const char gladestring [] = 
{
  "<?xml version=\"1.0\" ?><!-- Generated with glade 3.18.3 --><interface><requires lib=\"gtk+\" ve"
  "rsion=\"3.12\"/><!-- interface-license-type gplv3 --><!-- interface-name Gtk3Run --><!-- interfa"
  "ce-description Gtk3 Run Command --><!-- interface-authors J. M. Becker <cyberpunkspike@gmail.com"
  "> --><object class=\"GtkEntryCompletion\" id=\"entrycompletion1\"><property name=\"text_column\""
  ">0</property><signal handler=\"cb_matchselected\" name=\"match-selected\" swapped=\"no\"/><child"
  "><object class=\"GtkCellRendererText\" id=\"textCellRenderer\"><property name=\"ypad\">1</proper"
  "ty></object><attributes><attribute name=\"text\">0</attribute></attributes></child></object><obj"
  "ect class=\"GtkWindow\" id=\"window1\"><property name=\"can_focus\">False</property><property na"
  "me=\"title\" translatable=\"yes\">Run Command</property><property name=\"resizable\">False</prop"
  "erty><property name=\"window_position\">center</property><property name=\"type_hint\">dialog</pr"
  "operty><property name=\"decorated\">False</property><signal handler=\"cb_destroy\" name=\"destro"
  "y\" swapped=\"no\"/><child><object class=\"GtkBox\" id=\"box1\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\"orientation\">vertical</"
  "property><child><object class=\"GtkEntry\" id=\"entry1\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"margin_left\">4</property><prope"
  "rty name=\"margin_right\">4</property><property name=\"margin_top\">4</property><property name=\""
  "width_chars\">60</property><property name=\"caps_lock_warning\">False</property><property name=\""
  "primary_icon_activatable\">False</property><property name=\"secondary_icon_activatable\">False</"
  "property><property name=\"primary_icon_sensitive\">False</property><property name=\"secondary_ic"
  "on_sensitive\">False</property><property name=\"placeholder_text\" translatable=\"yes\">Run Comm"
  "and:</property><property name=\"completion\">entrycompletion1</property><property name=\"input_h"
  "ints\">GTK_INPUT_HINT_WORD_COMPLETION | GTK_INPUT_HINT_NONE</property><signal handler=\"cb_activ"
  "ate\" name=\"activate\" object=\"statusbar1\" swapped=\"no\"/><signal handler=\"cb_changed\" nam"
  "e=\"changed\" swapped=\"no\"/><signal handler=\"cb_keypress\" name=\"key-press-event\" swapped=\""
  "no\"/></object><packing><property name=\"expand\">False</property><property name=\"fill\">True</"
  "property><property name=\"position\">1</property></packing></child><child><object class=\"GtkSta"
  "tusbar\" id=\"statusbar1\"><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"margin_left\">12</property><property name=\"margin_right\">12<"
  "/property><property name=\"margin_start\">10</property><property name=\"margin_end\">10</propert"
  "y><property name=\"orientation\">vertical</property><signal handler=\"cb_pushed\" name=\"text-pu"
  "shed\" swapped=\"no\"/></object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">True</property><property name=\"position\">2</property></packing></child></object></c"
  "hild></object></interface>"
};
